# Generated by Django 5.1.7 on 2025-03-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_basic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='phone',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
