# Generated by Django 5.1.7 on 2025-03-10 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_basic_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='image',
            field=models.ImageField(upload_to='images/avatar.png'),
        ),
    ]
