# Generated by Django 5.1.7 on 2025-03-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_basic_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic',
            name='image',
        ),
        migrations.AddField(
            model_name='basic',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='photos/avatars/sa-'),
        ),
    ]
