# Generated by Django 5.1.7 on 2025-03-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_basic_image_basic_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic',
            name='instagram',
        ),
    ]
