# Generated by Django 5.1.7 on 2025-03-11 05:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_basic_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True)),
                ('text', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
    ]
