# Generated by Django 5.1.7 on 2025-03-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_academic_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic',
            name='date',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
